spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8080

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false  #表示是否将自己注册到Eureka Server，默认true
    fetch-registry: false  #表示是否从Eureka Server获取注册信息，默认true
    #在默认配置下，改服务注册中心也会将自己作为客户端来尝试注册它自己，所以需要禁用它的客户端注册行为
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka;
