#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles:
#    active: peer2
#
#server:
#  port: 8002
#
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    service-url:
#      defaultZone: http://peer1:8001/eureka/
#  server:
#   enable-self-preservation: false
#
