spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lh123456
  jpa:
    open-in-view: true


env: dev
