spring:
  application:
    name: spring-cloud-stream-producer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      bindings:
        example-topic-output:
#          producer:    #消费分区的配置
#            partitionKeyExpression: payload
#            partitionCount: 2
          destination: topic


server:
  port: 8090


