spring:
  application:
    name: spring.cloud.config.client
  cloud:
    bus:
      trace:
        enabled: true   #开启消息追踪
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 8051

management:
  endpoints:
    web:
      exposure:
        include: "*" #springboot 1.5.X 以上默认开通了安全认证


