spring:
  application:
    name: spring.cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lhuangcom/spring-boot #配置git仓库地址
          search-paths: blob #配置仓库路径
          default-label: master #配置仓库的分支
    bus:
      trace:
        enabled: true   #开启消息追踪
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/   # 注册中心eurka地址

management:
  security:
    enabled: false #springboot 1.5.X 以上默认开通了安全认证
encrypt:
  key: lhuang
